# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

# config file for development,  DELETE IT IF YOU WANT.


## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : 雪树网
description: > # this means to ignore newlines until "Language & timezone"
  雪树网 for development.
hrefhead: ''

## => Language and Timezone
##############################
lang: "zh-Hans" # the language of your site, default as "en"
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : organization # "person" (default), "organization"
  name      : 上海雪树科技有限公司
  url       :
  avatar    : /assets/apple-touch-icon.png
  bio: >
    上海雪树科技 for development.
  email     : asnowtree@163.com
  # facebook  : 1
  # twitter   : 1
  # weibo     : 1
  # googleplus: 1
  # telegram  : 1
  # medium    : 1
  # zhihu     : 1
  # douban    : 1
  # linkedin  : 1
  github    : asnowtree
  # npm       : 1


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: asnowtree/asnowtree.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: "h1,h2,h3,h4,h5,h6" # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: false # false (default), true
mathjax_autoNumber: false # false (default), true

## Mermaid
mermaid: false # false (default), true

## Chart
chart: false # false (default), true


## => Paginate
##############################
paginate: 10
paginate_path: /article/page:num # don't change this unless for special need


## => Sources
##############################
sources: bootcdn # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: asnowtree # false (default), "disqus", "gitalk", "valine", "custom"

  asnowtree:
    id: akey
  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : # LeanCloud App id
    app_key     : # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    # custom_search_engine_id: 017643444788069204610:4gvhea_mvga # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: false # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
# permalink   : categories/:year/date
# permalink   : none
# permalink   : date
# permalink   : pretty
permalink   : /article/:categories/:year-:month-:day-:title
# permalink   : /article/:categories/:year-:month-:day-:title/
exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  # - /docs
  - /node_modules
  # - /screenshots
  # - /test
  - /vendor
  - /_posts
  - /index.html

collections_dir: docs
collections:
  # docs:
    # permalink: "/:collection/:path/"
    # output: true
  # sample_page:
    # output: true
  # sample_articles:
    # output: true
  # sample_languages:
    # output: true
  # sample_games:
    # output: true
defaults:
  ## home
  - scope:
      path: "article"
    values:
      articles:
        excerpt_type: html
  ## posts
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      # category: post
      aside:
        toc: true
      # show_edit_on_github: true
      show_subscribe: false
      pageview: true
      lightbox: true
  ## samples
  - scope:
      path: ""
      type: sample_page
    values:
      nav_key: samples-p
  - scope:
      path: ""
      type: sample_articles
      pageview: true
    values:
      nav_key: samples-a
      show_date: false
  - scope:
      path: ""
      type: sample_languages
    values:
      layout: article
      nav_key: samples
      show_date: false
  ## docs
  - scope:
      path: "_docs/en"
    values:
      layout: article
      nav_key: docs
      sidebar:
        nav: docs-en
      license: true
      aside:
        toc: true
      show_edit_on_github: false
      show_date: false
      lightbox: true
  - scope:
      path: "_docs/zh"
    values:
      layout: article
      nav_key: docs
      sidebar:
        nav: docs-zh
      license: true
      aside:
        toc: true
      lang: zh
      show_edit_on_github: false
      show_date: false
      lightbox: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

data_dir: /docs/_data
