on:
  push:
    branches:
      - master
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:asnowtree/website.git"
          source_branch: "master"
          destination_repo: "git@e.coding.net:asnowtree/platform/website.git"
          destination_branch: "github"
          ssh_private_key: ${{ secrets.SYNCCODING }} # optional
          source_ssh_private_key: ${{ secrets.SYNCCODING }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.SYNCCODING }} # optional, will override `SSH_PRIVATE_KEY`