name: Build and deploy Jekyll documentation site

on:
  push:
    branches:
      - page

env:
  RUBY_VERSION: 3.1.2

jobs:
  deploy_docs:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    runs-on: 'ubuntu-latest'
    env:
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Build site
        run: |
          bundle exec jekyll build --config ./docs/_config.yml --trace
          ls
        env:
          # For jekyll-github-metadata
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
